# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagerprofile',
            name='joined_date',
            field=models.DateField(auto_now=True),
        ),
    ]
