# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170620_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerprofile',
            name='camera_type',
            field=models.CharField(choices=[('CAN', 'Cannon'), ('KOD', 'Kodiak'), ('NIK', 'Nikon'), ('SON', 'Sony'), ('IP', 'iPhone')], default='CAN', max_length=3),
        ),
        migrations.AlterField(
            model_name='imagerprofile',
            name='photography_style',
            field=models.CharField(choices=[('BW', 'Black and White'), ('PAN', 'Panorama'), ('PORT', 'Portrait'), ('LAND', 'Landscape'), ('FILM', 'Film')], default='BW', max_length=5),
        ),
    ]
